### ISSUE TITLE
Make map view more responsive (larger map view) - or full-screen mode

### ISSUE THREAD

**Issue by andreasneumann** [qgis/qgis-js#15]
It would be great to have either a "full-screen" mode or a more responsive map view.

On my relatively large screen I only get a small map view - see screenshot below

![grafik](https://github.com/qgis/qgis-js/assets/884476/3ac70b85-5b21-4e67-8e5a-6309c0b80258)

Alternatively (or in addition) it would be cool to have a "full-screen" button for the map.

Of course this is all "low priority" - but maybe not that hard to implement.

**Comment by boardend** [comment]
This was an easy one :smile: 

Wait for the next [build job](https://github.com/qgis/qgis-js/actions/runs/6875694373) to finish, then you can try it out
