### ISSUE TITLE
Map themes in QGIS should be exposed to the JS API

### ISSUE THREAD

**Issue by andreasneumann** [qgis/qgis-js#17]
The JS interface should support the following functionality:

- listing of all map themes in the project
- switch visibility of layers and styles according to a map theme provided in the API

That way we can add predefined combinations of layer visibilities and/or style combinations without having the user to switch many layers one after the other.

![grafik](https://github.com/qgis/qgis-js/assets/884476/7a085100-5862-4074-9548-1f94384858ed)

See also [QgsMapThemeCollection](https://api.qgis.org/api/classQgsMapThemeCollection.html) Class

**Comment by boardend** [comment]
Starting with qgis-js `0.0.2` map themes are part of the API.

This can also be tested with "Demo: World GPKG" on [GitHub Pages](https://qgis.github.io/qgis-js/)
