### ISSUE TITLE
Layer opacity below 1 results in unwanted graying effect

### ISSUE THREAD

**Issue by amuedespacher** [qgis/qgis-js#22]
When setting the opacity of a map layer to some value below 1 (e.g. 0.5), the map layer is displayed in a gray-ish color.

Steps to reproduce:
* Open sample page (https://qgis.github.io/qgis-js/)
* Select any of the rendering types (ol XYZ, ol Canvas, or JS)
* Set layer opacity to e.g. 0.5

Actual result:
* Map layer is displayed with a grayish tint.

Expected result:
* When reducing the layer opacity, the layer should maintain its original color quality, becoming more transparent without a gray overlay. The colors should remain true to their original hue, and only in terms of transparency.

Tested both with the sample project "village" and an own QGIS project.

Example:
Opacity = 1:
<img width="1516" alt="opacity-1" src="https://github.com/qgis/qgis-js/assets/1437209/aa7a27bf-e9e9-4de0-b837-9f4c3d7e5a5a">

Opacity < 1:
<img width="1505" alt="opacity-below-1" src="https://github.com/qgis/qgis-js/assets/1437209/2c5a259c-ffb2-441b-8236-119fc42ea47d">

**Comment by boardend** [comment]
This is [fixed](https://github.com/qgis/qgis-js/pull/24) and deployed to [GitHub Pages](https://qgis.github.io/qgis-js/)

If not urgent, I will have a look at the other new issues and then create a new npm version with them together..?
