### ISSUE TITLE
Relative SVG files do not render

### ISSUE THREAD

**Issue by andreasneumann** [qgis/qgis-js#26]
The attached project uses SVG files for rendering points. The SVG files are in a subfolder and are attached as relatives paths. However, they don't render correctly, but the question mark replacement symbol is shown instead.

This is how they should render:

![grafik](https://github.com/qgis/qgis-js/assets/884476/06bea0ae-0d74-48af-8863-c5551468dc95)

and this is how they render in qgis-wasm:

![grafik](https://github.com/qgis/qgis-js/assets/884476/018db79a-eb81-40e5-a96e-752a0755857a)

Is this an issue with the epxression engine or relativ paths treatment, or the wasm file system?

**Comment by andreasneumann** [comment]
[Klimaschutzgesetz_2056.zip](https://github.com/qgis/qgis-js/files/14083566/Klimaschutzgesetz_2056.zip)

The zip file contains the project, geopackage and SVG files.

**Comment by boardend** [comment]
With "Open local project" all the files, including the `.svg`s, get added to Emscripten FS in `/upload/projects/`

With the following formula, the symbols get rendered: `'/upload/projects/Klimaschutzgesetz_2056/kantonswappen/' || kanton_abkuerzung || '.svg'`

A nice solution would be to use `@project_home` or `@project_folder`, but both variables are only populated on desktop but not in qgis-js... Will have to investigate that further.

**Comment by boardend** [comment]
@wonder-sk Do you have an idea why @project_home and @project_folder are missing? Maybe a thread local / environment variable that is not available on the workers?

**Comment by andreasneumann** [comment]
It seems that other global variables (such as @qgis_platform and @qgis_os_name also don't work.

I think @qgis_platform should output something like 'wasm', 'qgis-js' or similar.

**Comment by andreasneumann** [comment]
oh - and also the variable @map_scale isn't working.

This one is super important for symbology and labeling rules.

Will open a separate issue for support of variables.

**Comment by boardend** [comment]
@andreasneumann With the fix from #29/#33, you should be able to use `@project_folder` to address this problem.

But in theory, this should not be necessary if you have set "Save paths" to "Relative" in the project properties. So I will leave this issue open to do some further investigations.

**Comment by amuedespacher** [comment]
@boardend , using relative paths (in combination with the abovementioned "relative" path setting on the project) works fine now. Thanks!
