### ISSUE TITLE
Global Variables not supported

### ISSUE THREAD

**Issue by andreasneumann** [qgis/qgis-js#29]
Many global variables are not supporte, such as:

- @map_scale
- @qgis_platform
- @qgis_os_name
- @qgis_locale
- @qgis_release_name
- @qgis_version

etc.

Tested with writing out the variables with COALESCE in a label.

See also issue #26

**Comment by boardend** [comment]
The merged pull request fixes this issue by adding an `ExpressionContext` to `renderImage()` and `renderXYZTile()`. Tested with `@map_scale`,  `@qgis_version` and `@project_folder` (from #26)

**Comment by andreasneumann** [comment]
@boardend - great - I am very much looking forward to using the variables in the future!
