### ISSUE TITLE
qgis-js/utils - loadRemoteProjects cannot handle files in subdirectories

### ISSUE THREAD

**Issue by amuedespacher** [qgis/qgis-js#31]
Steps to reproduce:
* Create a QGIS project with files in sub-folders
* Embed project as a "remote project" with @qgis-js/utils
* Open project in QGIS.js

Actual result:
* files in subdirectories are not processed

Expected result:
* files in subdirectories are processed

Current code: https://github.com/qgis/qgis-js/blob/main/packages/qgis-js-utils/src/fs/RemoteProject.ts

**Comment by boardend** [comment]
[RemoteProject](https://github.com/qgis/qgis-js/blob/main/packages/qgis-js-utils/src/fs/RemoteProject.ts)s are lacking the `subFoldersToCreate`-logic from [LocalProject](https://github.com/qgis/qgis-js/blob/main/packages/qgis-js-utils/src/fs/LocalProject.ts#L35).Therefore subdirectories work with local projects, but not with remote projects.

There is potential to share this logic between all `Project`-subclasses. Will look into that.

**Comment by amuedespacher** [comment]
Successfully tested with folders and subfolders. Thanks for the fix, @boardend.
